version: "3.8"
services:
  teamable-app:
    image: teamable-dev:v1
    ports:
      - 8080:8080
  mongodb:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=ernest
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    volumes:
      - mongo-data:/data/db
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=ernest
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local