version: "3.8"
services:
  db:
    image: mongo
    restart: always
    networks:
      - appNetwork
    
  site:
    image: teamable-app:v1
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=company_db
    networks:
      - appNetwork
  
  express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
    ports:
      - 8081:8081
    networks:
      - appNetwork

networks:
  appNetwork:
    name: mongo-network
    external: true

   